version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: commentdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
      - /app/frontend # 👈 IGNORE frontend folder in backend container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://nest:nestpass@postgres:5432/commentdb
      JWT_SECRET: supersecretkey
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

volumes:
  pgdata:
